const TEXT = {
  en: {
    appTitle: "EDI LC APF",
    appHeaderTitle: "ACCESS TO PRODUCTION FILES",
    headerLabel: "Quick links",
    home: "Home",
    homeTitle: "Quick access",
    homeSubtitle:
      "Open links by business unit and keep the list updated without backend code changes.",
    homeHint:
      "Choose a business unit below or open the manager to update links instantly.",
    legacySeed: "Starter data loaded",
    localChanges: "Local changes active",
    openManager: "Add New Partner",
    closeManager: "Close form",
    openBu: "Open business unit",
    entriesLoaded: "connections loaded",
    goToSection: "Go to section",
    currentSection: "Current section",
    noEntries: "No entries are available in this section yet.",
    noLinkAvailable: "No link is available here yet.",
    emptyHint:
      "Use the manager to add the first link for this business unit and section.",
    welcomeTitle: "Business Unit Overview",
    welcomeCopy:
      "Use the left menu to browse links for this business unit. New links can be added directly from the manager.",
    backupContact: "Backup contact",
    directoryLink: "Link",
    openDirectory: "Open link",
    searchPlaceholder: "Search current entries",
    clear: "Clear",
    addEntry: "Add link",
    addPartnerTitle: "Add New Partner",
    updateEntry: "Save changes",
    editEntry: "Edit",
    deleteEntry: "Remove",
    cancel: "Cancel",
    exportData: "Export data",
    importData: "Import data",
    resetData: "Reset starter data",
    managerTitle: "Add New Partner",
    managerCopy:
      "Changes are saved in this browser immediately. Export the JSON when you want to move the updated links elsewhere.",
    section: "Section",
    businessUnit: "Business unit",
    label: "Label",
    url: "Path or full URL",
    urlPlaceholder: "/B2BI_archives/... or full URL",
    contact: "Backup email or note",
    downloadTemplate: "Download template",
    importBulk: "Import bulk",
    bulkTemplateReady: "Bulk template downloaded.",
    bulkImportSuccess: "Bulk import completed: {added} added, {updated} updated.",
    bulkImportEmpty: "No valid bulk rows were found. Please use the downloaded template.",
    bulkImportError:
      "Unable to import the bulk file right now. Please check the template and try again.",
    saveStateLocal: "Saved in browser storage",
    csvSeedLabel: "Starter data loaded",
    quickAccess: "Quick access",
    supportTitle: "Need support?",
    supportMessage:
      "If the site is not working as expected, contact the support team directly.",
    supportButton: "Email support",
    documentation: "Documentation",
    sftp: "SFTP",
    certificate: "Certificate",
    poweredManagedBy: "powered and managed by",
    supportColumn: "Emergency contact",
    productionFiles: "Production Files",
    reception: "Reception",
    emission: "Emission",
    integrationReports: "Integration Reports",
    printDocuments: "Documents available for printing",
    mgLotsSap: "MG Lots <-> SAP Interfaces",
    interfaceFiles: "Interface files",
    integrationLogs: "Integration logs",
    annonces: "Customer announcement files",
    scans: "Laser scans",
    annoncesCarrierIod: "Carrier IOD announcement files",
    extractions: "IOD sent to customers",
    refclients: "Customer references",
    extractionAnnonceCarrier: "Announcements sent to carriers",
    integration: "Announcement integration reports",
    collas: "Laser scan integration reports",
    integrationIodCarrier: "Carrier IOD integration reports",
    impression: "Documents for printing",
    saisie1SAP2MGlots: "Entry 1 (SAP -> MG Lots)",
    saisie2MGlots2SAP: "Entry 2 (MG Lots -> SAP)",
    crIntgSaisie1SAP2MGlots: "Integration report entry 1",
    crIntgSaisie2MGlots2SAP: "Integration report entry 2",
    loginAccessTitle: "Access to Production file",
    loginVersion: "version 2.2",
    userId: "UserId",
    userIdPlaceholder: "Enter your UserId",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter your password",
    signIn: "Sign in",
    clientWelcomeBack: "Welcome back",
    clientWelcomeCopy: "Client access is ready. Continue directly to the portal.",
    adminMode: "admin mode",
    backToClientLogin: "back to client login",
    logout: "Logout",
    loginErrorAdmin: "Admin access details are not correct.",
    loginErrorClient: "Client access details are not correct.",
    savePartnerError:
      "Unable to save the partner right now. Please make sure the local save service is running.",
    removePartnerError:
      "Unable to remove the partner right now. Please make sure the local save service is running.",
    loadingDirectories: "Loading directories..."
  },
  fr: {
    appTitle: "EDI LC APF",
    appHeaderTitle: "ACCES AUX FICHIERS DE PRODUCTION",
    headerLabel: "Acces rapide",
    home: "Accueil",
    homeTitle: "Acces rapide",
    homeSubtitle:
      "Ouvrez les liens par business unit et gardez la liste a jour sans changement de code backend.",
    homeHint:
      "Choisissez une business unit ci-dessous ou ouvrez le gestionnaire pour mettre a jour les liens instantanement.",
    legacySeed: "Base initiale chargee",
    localChanges: "Modifications locales actives",
    openManager: "Ajouter un nouveau partenaire",
    closeManager: "Fermer le formulaire",
    openBu: "Ouvrir la business unit",
    entriesLoaded: "connexions chargees",
    goToSection: "Ouvrir la section",
    currentSection: "Section actuelle",
    noEntries: "Aucune entree disponible pour cette section.",
    noLinkAvailable: "Aucun lien n'est disponible ici pour le moment.",
    emptyHint:
      "Utilisez le gestionnaire pour ajouter le premier lien de cette business unit et de cette section.",
    welcomeTitle: "Vue d'ensemble de la Business Unit",
    welcomeCopy:
      "Utilisez le menu de gauche pour parcourir les liens de cette business unit. De nouveaux liens peuvent etre ajoutes directement depuis le gestionnaire.",
    backupContact: "Email de secours",
    directoryLink: "Lien",
    openDirectory: "Ouvrir le lien",
    searchPlaceholder: "Rechercher dans les entrees",
    clear: "Effacer",
    addEntry: "Ajouter un lien",
    addPartnerTitle: "Ajouter un nouveau partenaire",
    updateEntry: "Enregistrer",
    editEntry: "Modifier",
    deleteEntry: "Supprimer",
    cancel: "Annuler",
    exportData: "Exporter les donnees",
    importData: "Importer les donnees",
    resetData: "Reinitialiser la base",
    managerTitle: "Ajouter un nouveau partenaire",
    managerCopy:
      "Les changements sont sauvegardes immediatement dans ce navigateur. Exportez le JSON si vous voulez reutiliser les liens ailleurs.",
    section: "Section",
    businessUnit: "Business unit",
    label: "Libelle",
    url: "Chemin ou URL complete",
    urlPlaceholder: "/B2BI_archives/... ou URL complete",
    contact: "Email de secours ou note",
    downloadTemplate: "Telecharger le modele",
    importBulk: "Importer en masse",
    bulkTemplateReady: "Le modele d'import a ete telecharge.",
    bulkImportSuccess:
      "Import en masse termine : {added} ajoutes, {updated} mis a jour.",
    bulkImportEmpty:
      "Aucune ligne valide n'a ete trouvee. Veuillez utiliser le modele telecharge.",
    bulkImportError:
      "Impossible d'importer le fichier en masse pour le moment. Verifiez le modele et reessayez.",
    saveStateLocal: "Sauvegarde dans le navigateur",
    csvSeedLabel: "Base initiale chargee",
    quickAccess: "Acces rapide",
    supportTitle: "Besoin d'aide ?",
    supportMessage:
      "Si le site ne fonctionne pas comme prevu, contactez directement l'equipe support.",
    supportButton: "Envoyer un email",
    documentation: "Documentation",
    sftp: "SFTP",
    certificate: "Certificat",
    poweredManagedBy: "gere et maintenu par",
    supportColumn: "Email de secours",
    productionFiles: "Fichiers de production",
    reception: "Reception",
    emission: "Emission",
    integrationReports: "Comptes rendus d'integration",
    printDocuments: "Documents disponibles pour impression",
    mgLotsSap: "Interfaces MG Lots <-> SAP",
    interfaceFiles: "Fichiers interfaces",
    integrationLogs: "CR integrations",
    annonces: "Annonces clients",
    scans: "Scans laser",
    annoncesCarrierIod: "IOD sous-traitants",
    extractions: "IOD transmis aux clients",
    refclients: "Referentiels clients",
    extractionAnnonceCarrier: "Annonces vers sous-traitants",
    integration: "CR int. annonces",
    collas: "CR int. scans laser",
    integrationIodCarrier: "CR int. IOD sous-traitants",
    impression: "Documents pour impression",
    saisie1SAP2MGlots: "Saisie 1 (SAP -> MG Lots)",
    saisie2MGlots2SAP: "Saisie 2 (MG Lots -> SAP)",
    crIntgSaisie1SAP2MGlots: "CR int. saisie 1",
    crIntgSaisie2MGlots2SAP: "CR int. saisie 2",
    loginAccessTitle: "Acces au fichier de production",
    loginVersion: "version 2.2",
    userId: "Identifiant",
    userIdPlaceholder: "Entrez votre identifiant",
    passwordLabel: "Mot de passe",
    passwordPlaceholder: "Entrez votre mot de passe",
    signIn: "Se connecter",
    clientWelcomeBack: "Bon retour",
    clientWelcomeCopy: "L'acces client est pret. Continuez directement vers le portail.",
    adminMode: "mode admin",
    backToClientLogin: "retour a la connexion client",
    logout: "Deconnexion",
    loginErrorAdmin: "Les informations admin ne sont pas correctes.",
    loginErrorClient: "Les informations client ne sont pas correctes.",
    savePartnerError:
      "Impossible de sauvegarder le partenaire pour le moment. Verifiez que le service local est en cours d'execution.",
    removePartnerError:
      "Impossible de supprimer le partenaire pour le moment. Verifiez que le service local est en cours d'execution.",
    loadingDirectories: "Chargement des repertoires..."
  },
  de: {
    appTitle: "EDI LC APF",
    appHeaderTitle: "ZUGANG ZU PRODUKTIONSDATEIEN",
    headerLabel: "Schnellzugriff",
    home: "Start",
    homeTitle: "Schnellzugriff",
    homeSubtitle:
      "Oeffnen Sie Links nach Business Unit und halten Sie die Liste ohne Backend-Code-Aenderungen aktuell.",
    homeHint:
      "Waehlen Sie unten eine Business Unit oder oeffnen Sie den Manager fuer sofortige Anpassungen.",
    legacySeed: "Startdaten geladen",
    localChanges: "Lokale Aenderungen aktiv",
    openManager: "Neuen Partner hinzufuegen",
    closeManager: "Formular schliessen",
    openBu: "Business Unit oeffnen",
    entriesLoaded: "Verbindungen geladen",
    goToSection: "Zur Sektion",
    currentSection: "Aktuelle Sektion",
    noEntries: "Fuer diese Sektion sind noch keine Eintraege vorhanden.",
    noLinkAvailable: "Hier ist noch kein Link verfuegbar.",
    emptyHint:
      "Verwenden Sie den Manager, um den ersten Link fuer diese Business Unit und Sektion hinzuzufuegen.",
    welcomeTitle: "Business-Unit-Uebersicht",
    welcomeCopy:
      "Nutzen Sie das linke Menue, um Links fuer diese Business Unit zu durchsuchen. Neue Links koennen direkt im Manager angelegt werden.",
    backupContact: "Notfallkontakt",
    directoryLink: "Link",
    openDirectory: "Link oeffnen",
    searchPlaceholder: "Aktuelle Eintraege durchsuchen",
    clear: "Leeren",
    addEntry: "Link hinzufuegen",
    addPartnerTitle: "Neuen Partner hinzufuegen",
    updateEntry: "Aenderungen speichern",
    editEntry: "Bearbeiten",
    deleteEntry: "Entfernen",
    cancel: "Abbrechen",
    exportData: "Daten exportieren",
    importData: "Daten importieren",
    resetData: "Startdaten zuruecksetzen",
    managerTitle: "Neuen Partner hinzufuegen",
    managerCopy:
      "Aenderungen werden sofort in diesem Browser gespeichert. Exportieren Sie das JSON, wenn Sie die aktualisierten Links woanders verwenden wollen.",
    section: "Sektion",
    businessUnit: "Business Unit",
    label: "Bezeichnung",
    url: "Pfad oder vollstaendige URL",
    urlPlaceholder: "/B2BI_archives/... oder vollstaendige URL",
    contact: "E-Mail oder Hinweis",
    downloadTemplate: "Vorlage herunterladen",
    importBulk: "Massenimport",
    bulkTemplateReady: "Die Importvorlage wurde heruntergeladen.",
    bulkImportSuccess:
      "Massenimport abgeschlossen: {added} hinzugefuegt, {updated} aktualisiert.",
    bulkImportEmpty:
      "Keine gueltigen Importzeilen gefunden. Bitte verwenden Sie die heruntergeladene Vorlage.",
    bulkImportError:
      "Die Massendatei kann gerade nicht importiert werden. Bitte pruefen Sie die Vorlage und versuchen Sie es erneut.",
    saveStateLocal: "Im Browser gespeichert",
    csvSeedLabel: "Startdaten geladen",
    quickAccess: "Schnellzugriff",
    supportTitle: "Support benoetigt?",
    supportMessage:
      "Wenn die Seite nicht wie erwartet funktioniert, kontaktieren Sie bitte direkt das Support-Team.",
    supportButton: "Support per E-Mail",
    documentation: "Dokumentation",
    sftp: "SFTP",
    certificate: "Zertifikat",
    poweredManagedBy: "bereitgestellt und betreut von",
    supportColumn: "Notfallkontakt",
    productionFiles: "Produktionsdateien",
    reception: "Empfang",
    emission: "Versand",
    integrationReports: "Integrationsberichte",
    printDocuments: "Druckdokumente",
    mgLotsSap: "MG Lots <-> SAP Schnittstellen",
    interfaceFiles: "Schnittstellendateien",
    integrationLogs: "Integrationslogs",
    annonces: "Kundenankuendigungsdateien",
    scans: "Laserscans",
    annoncesCarrierIod: "Carrier-IOD-Ankuendigungsdateien",
    extractions: "An Kunden gesendete IOD",
    refclients: "Kundenreferenzen",
    extractionAnnonceCarrier: "Ankuendigungen an Carrier",
    integration: "Integrationsberichte Ankuendigungen",
    collas: "Integrationsberichte Laserscans",
    integrationIodCarrier: "Integrationsberichte Carrier IOD",
    impression: "Dokumente fuer den Druck",
    saisie1SAP2MGlots: "Eingabe 1 (SAP -> MG Lots)",
    saisie2MGlots2SAP: "Eingabe 2 (MG Lots -> SAP)",
    crIntgSaisie1SAP2MGlots: "Integrationsbericht Eingabe 1",
    crIntgSaisie2MGlots2SAP: "Integrationsbericht Eingabe 2",
    loginAccessTitle: "Zugang zur Produktionsdatei",
    loginVersion: "version 2.2",
    userId: "Benutzer-ID",
    userIdPlaceholder: "Benutzer-ID eingeben",
    passwordLabel: "Passwort",
    passwordPlaceholder: "Passwort eingeben",
    signIn: "Anmelden",
    clientWelcomeBack: "Willkommen zurueck",
    clientWelcomeCopy: "Der Client-Zugang ist bereit. Gehen Sie direkt zum Portal weiter.",
    adminMode: "Admin-Modus",
    backToClientLogin: "zurueck zum Client-Login",
    logout: "Abmelden",
    loginErrorAdmin: "Die Admin-Zugangsdaten sind nicht korrekt.",
    loginErrorClient: "Die Client-Zugangsdaten sind nicht korrekt.",
    savePartnerError:
      "Der Partner kann gerade nicht gespeichert werden. Bitte pruefen Sie, ob der lokale Speicherdienst laeuft.",
    removePartnerError:
      "Der Partner kann gerade nicht entfernt werden. Bitte pruefen Sie, ob der lokale Speicherdienst laeuft.",
    loadingDirectories: "Verzeichnisse werden geladen..."
  },
  it: {
    appTitle: "EDI LC APF",
    appHeaderTitle: "ACCESSO AI FILE DI PRODUZIONE",
    headerLabel: "Accesso rapido",
    home: "Home",
    homeTitle: "Accesso rapido",
    homeSubtitle:
      "Apri i link per business unit e mantieni l'elenco aggiornato senza modifiche al codice backend.",
    homeHint:
      "Scegli una business unit qui sotto o apri il gestore per aggiornare subito i link.",
    legacySeed: "Dati iniziali caricati",
    localChanges: "Modifiche locali attive",
    openManager: "Aggiungi nuovo partner",
    closeManager: "Chiudi modulo",
    openBu: "Apri business unit",
    entriesLoaded: "connessioni caricate",
    goToSection: "Vai alla sezione",
    currentSection: "Sezione attuale",
    noEntries: "Nessuna voce disponibile in questa sezione.",
    noLinkAvailable: "Nessun link disponibile qui al momento.",
    emptyHint:
      "Usa il gestore per aggiungere il primo link per questa business unit e sezione.",
    welcomeTitle: "Panoramica Business Unit",
    welcomeCopy:
      "Usa il menu a sinistra per consultare i link di questa business unit. Nuovi link possono essere aggiunti direttamente dal gestore.",
    backupContact: "Contatto di emergenza",
    directoryLink: "Link",
    openDirectory: "Apri link",
    searchPlaceholder: "Cerca nelle voci correnti",
    clear: "Pulisci",
    addEntry: "Aggiungi link",
    addPartnerTitle: "Aggiungi nuovo partner",
    updateEntry: "Salva modifiche",
    editEntry: "Modifica",
    deleteEntry: "Rimuovi",
    cancel: "Annulla",
    exportData: "Esporta dati",
    importData: "Importa dati",
    resetData: "Ripristina dati iniziali",
    managerTitle: "Aggiungi nuovo partner",
    managerCopy:
      "Le modifiche vengono salvate subito in questo browser. Esporta il JSON quando vuoi spostare i link aggiornati altrove.",
    section: "Sezione",
    businessUnit: "Business unit",
    label: "Etichetta",
    url: "Percorso o URL completo",
    urlPlaceholder: "/B2BI_archives/... o URL completo",
    contact: "Email di backup o nota",
    downloadTemplate: "Scarica modello",
    importBulk: "Importa in blocco",
    bulkTemplateReady: "Il modello per l'importazione e stato scaricato.",
    bulkImportSuccess:
      "Importazione completata: {added} aggiunti, {updated} aggiornati.",
    bulkImportEmpty:
      "Nessuna riga valida trovata. Usa il modello scaricato.",
    bulkImportError:
      "Impossibile importare il file in blocco in questo momento. Controlla il modello e riprova.",
    saveStateLocal: "Salvato nel browser",
    csvSeedLabel: "Dati iniziali caricati",
    quickAccess: "Accesso rapido",
    supportTitle: "Serve supporto?",
    supportMessage:
      "Se il sito non funziona come previsto, contatta direttamente il team di supporto.",
    supportButton: "Invia email al supporto",
    documentation: "Documentazione",
    sftp: "SFTP",
    certificate: "Certificato",
    poweredManagedBy: "gestito e supportato da",
    supportColumn: "Contatto di emergenza",
    productionFiles: "File di produzione",
    reception: "Ricezione",
    emission: "Emissione",
    integrationReports: "Report di integrazione",
    printDocuments: "Documenti disponibili per la stampa",
    mgLotsSap: "Interfacce MG Lots <-> SAP",
    interfaceFiles: "File interfaccia",
    integrationLogs: "Log di integrazione",
    annonces: "File avviso clienti",
    scans: "Scansioni laser",
    annoncesCarrierIod: "File avviso corriere IOD",
    extractions: "IOD inviati ai clienti",
    refclients: "Riferimenti clienti",
    extractionAnnonceCarrier: "Avvisi inviati ai corrieri",
    integration: "Report integrazione avvisi",
    collas: "Report integrazione scansioni laser",
    integrationIodCarrier: "Report integrazione IOD corriere",
    impression: "Documenti per la stampa",
    saisie1SAP2MGlots: "Inserimento 1 (SAP -> MG Lots)",
    saisie2MGlots2SAP: "Inserimento 2 (MG Lots -> SAP)",
    crIntgSaisie1SAP2MGlots: "Report integrazione inserimento 1",
    crIntgSaisie2MGlots2SAP: "Report integrazione inserimento 2",
    loginAccessTitle: "Accesso al file di produzione",
    loginVersion: "version 2.2",
    userId: "ID utente",
    userIdPlaceholder: "Inserisci il tuo ID utente",
    passwordLabel: "Password",
    passwordPlaceholder: "Inserisci la tua password",
    signIn: "Accedi",
    clientWelcomeBack: "Bentornato",
    clientWelcomeCopy: "L'accesso client e pronto. Continua direttamente al portale.",
    adminMode: "modalita admin",
    backToClientLogin: "torna al login cliente",
    logout: "Esci",
    loginErrorAdmin: "Le credenziali admin non sono corrette.",
    loginErrorClient: "Le credenziali client non sono corrette.",
    savePartnerError:
      "Impossibile salvare il partner ora. Verifica che il servizio di salvataggio locale sia attivo.",
    removePartnerError:
      "Impossibile rimuovere il partner ora. Verifica che il servizio di salvataggio locale sia attivo.",
    loadingDirectories: "Caricamento directory..."
  },
  pl: {
    appTitle: "EDI LC APF",
    appHeaderTitle: "DOSTEP DO PLIKOW PRODUKCYJNYCH",
    headerLabel: "Szybki dostep",
    home: "Home",
    homeTitle: "Szybki dostep",
    homeSubtitle:
      "Otwieraj linki wedlug business unit i utrzymuj liste bez zmian w kodzie backendu.",
    homeHint:
      "Wybierz business unit ponizej albo otworz menedzer, aby od razu zaktualizowac linki.",
    legacySeed: "Dane poczatkowe zaladowane",
    localChanges: "Lokalne zmiany aktywne",
    openManager: "Dodaj nowego partnera",
    closeManager: "Zamknij formularz",
    openBu: "Otworz business unit",
    entriesLoaded: "polaczen zaladowano",
    goToSection: "Przejdz do sekcji",
    currentSection: "Biezaca sekcja",
    noEntries: "Brak wpisow w tej sekcji.",
    noLinkAvailable: "Brak dostepnego linku w tej sekcji.",
    emptyHint:
      "Uzyj menedzera, aby dodac pierwszy link dla tej business unit i sekcji.",
    welcomeTitle: "Przeglad Business Unit",
    welcomeCopy:
      "Uzyj lewego menu, aby przegladac linki tej business unit. Nowe linki mozna dodawac bezposrednio w menedzerze.",
    backupContact: "Kontakt awaryjny",
    directoryLink: "Link",
    openDirectory: "Otworz link",
    searchPlaceholder: "Szukaj w biezacych wpisach",
    clear: "Wyczysc",
    addEntry: "Dodaj link",
    addPartnerTitle: "Dodaj nowego partnera",
    updateEntry: "Zapisz zmiany",
    editEntry: "Edytuj",
    deleteEntry: "Usun",
    cancel: "Anuluj",
    exportData: "Eksportuj dane",
    importData: "Importuj dane",
    resetData: "Przywroc dane poczatkowe",
    managerTitle: "Dodaj nowego partnera",
    managerCopy:
      "Zmiany sa zapisywane od razu w tej przegladarce. Wyeksportuj plik JSON, jesli chcesz przeniesc zaktualizowane linki gdzie indziej.",
    section: "Sekcja",
    businessUnit: "Business unit",
    label: "Etykieta",
    url: "Sciezka lub pelny URL",
    urlPlaceholder: "/B2BI_archives/... lub pelny URL",
    contact: "Email awaryjny lub notatka",
    downloadTemplate: "Pobierz szablon",
    importBulk: "Import zbiorczy",
    bulkTemplateReady: "Szablon importu zostal pobrany.",
    bulkImportSuccess:
      "Import zbiorczy zakonczony: dodano {added}, zaktualizowano {updated}.",
    bulkImportEmpty:
      "Nie znaleziono prawidlowych wierszy. Uzyj pobranego szablonu.",
    bulkImportError:
      "Nie mozna teraz zaimportowac pliku zbiorczego. Sprawdz szablon i sprobuj ponownie.",
    saveStateLocal: "Zapisano w przegladarce",
    csvSeedLabel: "Dane poczatkowe zaladowane",
    quickAccess: "Szybki dostep",
    supportTitle: "Potrzebujesz wsparcia?",
    supportMessage:
      "Jesli strona nie dziala zgodnie z oczekiwaniami, skontaktuj sie bezposrednio z zespolem wsparcia.",
    supportButton: "Wyslij email do wsparcia",
    documentation: "Dokumentacja",
    sftp: "SFTP",
    certificate: "Certyfikat",
    poweredManagedBy: "obslugiwane i zarzadzane przez",
    supportColumn: "Kontakt awaryjny",
    productionFiles: "Pliki produkcyjne",
    reception: "Przyjecie",
    emission: "Wysylka",
    integrationReports: "Raporty integracji",
    printDocuments: "Dokumenty do druku",
    mgLotsSap: "Interfejsy MG Lots <-> SAP",
    interfaceFiles: "Pliki interfejsu",
    integrationLogs: "Logi integracji",
    annonces: "Pliki zapowiedzi klienta",
    scans: "Skany laserowe",
    annoncesCarrierIod: "Pliki zapowiedzi przewoznika IOD",
    extractions: "IOD wyslane do klientow",
    refclients: "Referencje klientow",
    extractionAnnonceCarrier: "Zapowiedzi wyslane do przewoznikow",
    integration: "Raporty integracji zapowiedzi",
    collas: "Raporty integracji skanow laserowych",
    integrationIodCarrier: "Raporty integracji IOD przewoznika",
    impression: "Dokumenty do druku",
    saisie1SAP2MGlots: "Wpis 1 (SAP -> MG Lots)",
    saisie2MGlots2SAP: "Wpis 2 (MG Lots -> SAP)",
    crIntgSaisie1SAP2MGlots: "Raport integracji wpis 1",
    crIntgSaisie2MGlots2SAP: "Raport integracji wpis 2",
    loginAccessTitle: "Dostep do pliku produkcyjnego",
    loginVersion: "version 2.2",
    userId: "Id uzytkownika",
    userIdPlaceholder: "Wpisz swoje ID uzytkownika",
    passwordLabel: "Haslo",
    passwordPlaceholder: "Wpisz haslo",
    signIn: "Zaloguj sie",
    clientWelcomeBack: "Witamy ponownie",
    clientWelcomeCopy: "Dostep klienta jest gotowy. Przejdz bezposrednio do portalu.",
    adminMode: "tryb admina",
    backToClientLogin: "powrot do logowania klienta",
    logout: "Wyloguj",
    loginErrorAdmin: "Dane dostepu administratora sa nieprawidlowe.",
    loginErrorClient: "Dane dostepu klienta sa nieprawidlowe.",
    savePartnerError:
      "Nie mozna teraz zapisac partnera. Upewnij sie, ze lokalna usluga zapisu jest uruchomiona.",
    removePartnerError:
      "Nie mozna teraz usunac partnera. Upewnij sie, ze lokalna usluga zapisu jest uruchomiona.",
    loadingDirectories: "Ladowanie katalogow..."
  }
};

export function getText(language) {
  return TEXT[language] || TEXT.en;
}
