-- Oracle schema reference for the MyRota linked microsites.
-- ROTA stays on Firestore. These tables back the Oracle-powered microsites.

CREATE TABLE MYROTA_APF (
  ID VARCHAR2(120) PRIMARY KEY,
  BU VARCHAR2(16) NOT NULL,
  ENTRY_TYPE VARCHAR2(100) NOT NULL,
  LABEL VARCHAR2(300) NOT NULL,
  URL VARCHAR2(2000) NOT NULL,
  BACKUP_CONTACT VARCHAR2(300),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX MYR_APF_BU_TYPE_IDX
  ON MYROTA_APF (BU, ENTRY_TYPE);


CREATE TABLE MYROTA_DOCUMENTATION (
  ID VARCHAR2(120) PRIMARY KEY,
  TITLE VARCHAR2(300) NOT NULL,
  NOTE_TAG VARCHAR2(120) NOT NULL,
  BODY_TEXT CLOB NOT NULL,
  MEDIA_NAME VARCHAR2(500),
  MEDIA_TYPE VARCHAR2(200),
  MEDIA_DATA CLOB,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX MYR_DOC_UPD_IDX
  ON MYROTA_DOCUMENTATION (UPDATED_AT);


CREATE TABLE MYROTA_SFTP (
  ID VARCHAR2(120) PRIMARY KEY,
  PARTNER_NAME VARCHAR2(300) NOT NULL,
  CONNECTION_TYPE VARCHAR2(20) NOT NULL,
  HOST VARCHAR2(500) NOT NULL,
  PORT NUMBER(5) DEFAULT 22 NOT NULL,
  USERNAME VARCHAR2(300) NOT NULL,
  PASSWORD_VALUE VARCHAR2(300) NOT NULL,
  CONTACT_PERSON VARCHAR2(300) NOT NULL,
  NOTES CLOB,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX MYR_SFTP_UPD_IDX
  ON MYROTA_SFTP (UPDATED_AT);


CREATE TABLE MYROTA_CERTIFICATE (
  ID VARCHAR2(120) PRIMARY KEY,
  PARTNER_NAME VARCHAR2(300) NOT NULL,
  CERTIFICATE_TYPE VARCHAR2(120) NOT NULL,
  CONTACT_TEAM VARCHAR2(300) NOT NULL,
  ISSUED_DATE VARCHAR2(20) NOT NULL,
  EXPIRY_DATE VARCHAR2(20) NOT NULL,
  UPLOAD_NAME VARCHAR2(500),
  UPLOAD_TYPE VARCHAR2(200),
  UPLOAD_DATA CLOB,
  NOTES CLOB,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX MYR_CERT_EXP_IDX
  ON MYROTA_CERTIFICATE (EXPIRY_DATE);
